const list = [
    { name: "Dell", category: "Laptop", count: 12, price: 4200 },
    { name: "Sony curve", category: "TV", count: 7, price: 8900 },
    { name: "LG abc", category: "Screen", count: 21, price: 3100 },
    { name: "Mxyz n1", category: "Mouse", count: 9, price: 210 },
    { name: "Dell xyz", category: "Laptop", count: 12, price: 5700 },
    { name: "STT b51", category: "Power", count: 17, price: 130 },
    { name: "Samsung s5", category: "Mobile", count: 11, price: 6700 },
    { name: "iPad Pro", category: "Tablet", count: 3, price: 9500 },
    { name: "Toshiba xyz", category: "TV", count: 5, price: 4800 },
    { name: "LG Max", category: "Screen", count: 21, price: 3400 },
    { name: "Acer", category: "Laptop", count: 12, price: 2200 },
    { name: "MM Mouse", category: "Mouse", count: 9, price: 190 },
    { name: "HTC abc", category: "Mobile", count: 11, price: 7700 },
    { name: "Casper", category: "Laptop", count: 12, price: 2600 },
    { name: "iPad 6", category: "Tablet", count: 3, price: 3900 },
    { name: "BSY ggg", category: "Screen", count: 21, price: 2100 },
    { name: "Power abc", category: "Power", count: 17, price: 150 },
    { name: "Lenovo", category: "Laptop", count: 12, price: 4400 },
    { name: "FAR 22", category: "Mouse", count: 9, price: 310 },
    { name: "Sharp abc", category: "TV", count: 7, price: 5300 },
    { name: "iPad mini", category: "Tablet", count: 3, price: 2400 },
    { name: "iPhone 7", category: "Mobile", count: 11, price: 7900 },
    { name: "Apple TV", category: "TV", count: 7, price: 8800 },
    { name: "LG xyz", category: "Screen", count: 21, price: 3900 },
];